version: "3.2"

services:
  logs-zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    networks:
      - net-logs
    container_name: logs-zookeeper

  logs-kafka:
    image: wurstmeister/kafka
    container_name: logs-kafka
    ports:
      - 9092:9092
    networks:
      - net-logs
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://logs-kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: logs-zookeeper:2181
      KAFKA_CREATE_TOPICS: "task-queue:1:1:delete, status-queue:1:1:delete"
    depends_on:
      - logs-zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  logs-application:
    build:
      context: ./elkLogSystem
    volumes: 
    - ./logs:/opt/logs
    depends_on:
      - logs-zookeeper
      - logs-kafka
    ports:
      - 7080:8080
      
  logs-worker:
    build:
      context: ./worker
    volumes: 
    - ./logs:/opt/logs
    depends_on:
      - logs-zookeeper
      - logs-kafka


networks:
  net-logs:
    driver: bridge
