logging:
  file:
    name: /opt/logs/logs.log

spring:
  kafka:
    producer:
      bootstrap-servers: ${LOGS_KAFKA_SERVER:logs-kafka:9092}

thirdParty:
  api:
    url: ${THIRD_PARTY_URL:logs-third-party:8081}